SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users(
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(100) UNIQUE  NOT NULL,
	user_nickname VARCHAR(100)  NOT NULL,
	password VARCHAR(100)  NOT NULL,
	is_deleted TINYINT(1) DEFAULT 0
);